make rulerAPIPath configurable
cortexproject/cortex-tools pull request #19
Opened 2023-10-05 13:30 UTC by janwillies

Currently the ruler api path is hardcoded in cortex-tools. In some deployments the ruler api is available on a different path though. This PR makes the `rulerAPIPath` configurable

2023-10-31 10:22 UTC, janwillies commented
could you please take a look @friedrichg?

2023-11-01 13:09 UTC, friedrichg requested changes
I don't see why not. Just the yaml needs to be like the rest.

2023-11-01 13:09 UTC, friedrichg commented on pkg/client/client.go
> +	RulerAPIPath    string `yaml:"rulerAPIPath"`
```suggestion
	RulerAPIPath    string `yaml:"ruler_api_path"`
```

2023-11-01 13:43 UTC, janwillies commented
whoops, fixed now

2023-11-01 15:26 UTC, friedrichg approved these changes

2023-11-01 17:07 UTC, friedrichg commented
@janwillies can you accept/merge https://github.com/janwillies/cortex-tools/pull/1 ?

2023-11-01 17:46 UTC, merged